import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Greeting from '@/src/components/Greeting'
import styles from '../styles/Home.module.css'

// ! Next.js + React 18 Hydration Error:
// https://stackoverflow.com/a/71870995

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome!</h1>

        <Greeting />

        <div>
          <Link href="/about">
            <a>About Page</a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
